### ISSUE TITLE
CRE MVP

### ISSUE THREAD

**Issue by northdpole** [OWASP/www-project-integration-standards#22]
1. select 3 sources: ASVS, Cheatsheets and WSTG
2. pick small selection in ASVS, session mgmt and login functionality
3. mapping file is yaml of the proposed format [here](https://github.com/northdpole/www-project-integration-standards/blob/master/cres/demo01.yaml)
4. Build a CRE updater that reads mapping file and builds CRE-Source Relations and creates a markdown CRE table
5. Create CREs for a small selection of 2.
6. Link CREs from 5. to tool CRE mappings
7. Auto produce a visualization of complete CRE documents with CRE metadata, details and links

**Comment by ThunderSon** [comment]
Since we already have the Error logging ones, we can start off with that, and then have the session management ones.
We just need to add testing CRE IDs to the lists.

**Comment by northdpole** [comment]
MVP is here http://www.opencre.org/ and here https://github.com/owaSP/common-requirement-enumeration
