### ISSUE TITLE
Request to reference the OWASP Secure Headers Project 

### ISSUE THREAD

**Issue by righettod** [OWASP/www-project-integration-standards#44]
Hi,

What is the procedures/workflow/documents to reference the [OWASP Secure Headers Project](https://owasp.org/www-project-secure-headers/) into the integration schema and integration project?

Thank you very much in advance for your help 😃

**Comment by northdpole** [comment]
Hey, really sorry for the late answer, I've migrated this issue here https://github.com/OWASP/common-requirement-enumeration/issues/251 where we will work on it.

**Comment by righettod** [comment]
Hey, no problem, thanks for the feedback.

**Comment by jgadsden** [comment]
This can now be closed, @northdpole has added Secure Headers to the diagram in [OWASP/owasp.github.io#286](https://github.com/OWASP/owasp.github.io/pull/286#issuecomment-1793702245), Verficiation->Tools

**Comment by righettod** [comment]
OK I close it, thanks a lot for all the support and this project 🥇
