### ISSUE TITLE
Up-to-date Roadmap?

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-project-integration-standards#46]
https://owasp.org/www-project-integration-standards/#project-roadmap

Is still based in 2020/2021 😉

**Comment by kingthorin** [comment]
@northdpole I was just watching your Jan presentation to the board when I checked the site and noticed this 😀

**Comment by robvanderveer** [comment]
Good point. thanks! Will pick up.

**Comment by northdpole** [comment]
Resolved by Rob, thanks for reporting this!
