### ISSUE TITLE
Project update diagram - Operation

### ISSUE THREAD

**Issue by jptosso** [OWASP/www-project-integration-standards#48]
Please consider adding [OWASP Coraza](https://owasp.org/www-project-coraza-web-application-firewall/) into "Operation" section of the diagram. It runs OWASP Core Ruleset in-app or through proxies.

Thank you!

**Comment by jgadsden** [comment]
This can now be closed, @northdpole has added Coraza to the diagram in [OWASP/owasp.github.io#286](https://github.com/OWASP/owasp.github.io/pull/286#issuecomment-1793702245)
