### ISSUE TITLE
Request to reference CycloneDX

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-integration-standards#49]
Could we have the Wayfinder diagram modified to include the flagship project [OWASP CycloneDX](https://owasp.org/www-project-cyclonedx/) ?
Its natural place is in the Dependencies area under Implementation, beside Dependency-Check and Dependency-Track

**Comment by northdpole** [comment]
Sure, on it.

**Comment by jgadsden** [comment]
Thanks @northdpole , and could we also have some of the other OWASP Production projects?

* [Coraza](https://owasp.org/www-project-coraza-web-application-firewall/) added to Operation
* [WrongSecrets](https://owasp.org/www-project-wrongsecrets/) added to Training/Education
* [Secure Headers Project](https://owasp.org/www-project-secure-headers/) - probably Verification->Tools but also Implementation->Secure Libraries

Apologies for loading you up like this, and many thanks

**Comment by northdpole** [comment]
Done! https://github.com/OWASP/owasp.github.io/pull/286
